### ISSUE TITLE
Correct way to run vue-tslint?

### ISSUE THREAD

**Issue by chriszrc** [zhanba/vue-tslint#1]
Should I be executing the binary from ./node_modules/etc? And when I do that, I'm not seeing tslint reporting any errors, while running the normal `vue-cli-service serve` I see lots of tslint errors

**Comment by zhanba** [comment]
If you have vue-cli-service, why not use `vue-cli-service lint`? this project is build for old vue project that don't use vue-cli-service.

**Comment by zhanba** [comment]
I have add an example, you can run it and see the errors

**Comment by chriszrc** [comment]
Right, I tried `vue-cli-service lint` and it appears to be running eslint, even though when I run the project, it's definitely tslint that is generating errors. Thanks for responding-
